version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker run -d --rm --name chrome --shm-size 1024m -p 9222:9222 --cap-add SYS_ADMIN yukinying/chrome-headless-browser
      - run: npm install
      - run: npm test
